# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Personal info
name: Yash Vyas
title: Undergraduate Student, Computer Science
email: vyasy@myumanitoba.ca
# email_title: Email (Email title override)
phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://yash-vyas97.github.io/7889090-A2/

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  jekyll
instagram_username: yash_vyas97
linkedin_username: yash-vyas-8308a1205

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profileImage.png
about_content: | # this will include new lines to allow paragraphs
  I am a fourth year Computer Science and Math student at the University of Manitoba. I am passionate about Algorithms and Data Structures, Human-Computer Interaction and Artificial Intelligence.
  I also like to go to the gym and sketch in my free time.
# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  The programming languages, frameworks and technical services I am well aquainted with include:
  <mark>Git</mark>,
  <mark>MySQL</mark>,
  <mark>Java</mark>,
  <mark>C++</mark>
  <mark>React</mark>,
  <mark>Android Studio</mark> and
  <mark>Ruby</mark>
  <mark>JUnit</mark>


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Real time YouTube commenting - A Google chrome plugin
        additional_links:
          - title:  yash-vyas97 / Real-time-YouTube-chrome-plugin-extension. 
            icon: fab fa-github
            url: https://github.com/yash-vyas97/Real-time-YouTube-chrome-plugin-extension.
        quote: > A plugin that allows users to comment on videos based on video timing in real time.
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
        #Description about the work on/with the project
          - Created at the University of Toronto hackathon, NSBE Hacks 2022.
          - Applied <mark>Firebase<mark>, <mark>JavaScript<mark> and <mark>jQuery<mark> for real-time syncing of video comments.
     
      - layout: top-middle
        border: weak
        title: Pocket StockWatch
        additional_links:
          - title:  Application
            icon: fab fa-github
           
        quote: > A robust Stock Notification Application
        description: |
          - Created a servlet application for users to efficiently pick their favorite stocks and sends SMS notifications based on percentage changes of their favorite stocks
          
          - Built at the University of Manitoba annual DevClub hackathon with <mark>Ruby<mark> <mark>on<mark> <mark>Rails<mark> <mark>Twilio<mark> <mark>API<mark> and <mark>bootstrap<mark>.
          
          - Implemented log in and sign-up using <mark>OAuth<mark> in <mark>Ruby<mark> and developed <mark>Twilio<mark> <mark>script<mark> to send SMS notifications.
          
      - layout: top-middle
        border: weak
        title: Solanium
        quote: >
          Agriculture web application.
        description: |
          - A <mark>CRUD<mark> application that enables its users to connect with local farmers to buy fresh and organic food
          
          - Engineered RESTful API and setup relational data models.
          
          - Created using <mark>ReactJS<mark>, <mark>Laravel<mark> and backed by <mark>MySQL<mark>.
  
   - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Kellison Group LTD
        sub_title: Junior Software Engineering Intern
        caption: 5/2022 - Present
        link: https://opengovca.com/corporation/8887306
#         quote: >
#           Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          - Implementation of new metrics dashboard using Grafana and InfluxDB, and wrote scripts to import data from MySQL into Graphite and InflucDB. Automated database backup and encryption CRON job using AWS and SHA-256.
          - Implemented UI designer’s mockups of new email interfaces on the rails application which resulted in an 18% customer increase.
      
      - layout: left
        title: University Of Manitoba
        sub_title: Event Coordinator
        caption: 9/2022 - Present
        description: |
          - Oversaw event setup and layout at the various requested locations in University.
          - Administered employee payroll and scheduling.
      
      - layout: left
        title: Best Buy
        sub_title: Service desk technician
        caption: 1/2021 - 2/2022
        link: https://www.bestbuy.ca/en-ca?cmp=knc-c-71700000055262309-k-43700045991179434&gclid=Cj0KCQiAgaGgBhC8ARIsAAAyLfGqEs7_DiLrEf41AjGYPV4Db_LG0a6DBbaPr2HBpy1Tp-COuGL9yRYaAu7HEALw_wcB&gclsrc=aw.ds
        description: |
          - Regulated customer complaints.
          - Trained new employees.
 
   - title: Education
    layout: list
    content:
      - layout: top-middle
        title: University of Manitoba
        sub_title: Bachelor of Science in Computer Science (Honours) (Co-op option), Mathematics minor.
        caption: Expected 12/2023
   
   - title: Awards and Achievements
    layout: list
    content:
      - layout: left
        border: weak
        title: International Undergraduate Student Entrance Scholarship, University 1
        caption: 9/2019
        
      - layout: left
        border: weak
        title: Pearson Edexcel International Advanced Level Outstanding Learner
        sub_title: Ranked One globally in Core Mathematics 1 and 2.
        caption: 8/2018
        
      - layout: left
        border: weak
        title: Pearson Edexcel International GCSE Outstanding Learner
        sub_title: Ranked One globally in Further Pure Mathematics 2.
        caption: 8/2017

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
